nums=[1,2,3,4,5]
print(nums[1])
print(nums[2])
print(nums[3:1])
print(nums[1:2])
nums.append(3)
print(nums)
nums.insert(1,2)
print(nums)
nums.extend([1])
print(nums)
nums.remove(4)
print(nums)
del nums[1]
print(nums)
nums.pop(2)
print(nums)
len([1,2,3,4])
print(len(nums))
nums.reverse()
print(nums)
nums.copy()
print(nums)
print("4"in nums)
for nums in nums:
    print(nums)